import "./globals.css";
import type { Metadata } from "next";
import { Sawarabi_Mincho } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const sawarabi = Sawarabi_Mincho({
  subsets: ["latin"],
  weight: ["400", "400"],
});

export const metadata: Metadata = {
  title: "これ何のWiki?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`relative ${sawarabi.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
