import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_JP, Sawarabi_Mincho } from "next/font/google";
import Navbar from "./components/navbar/Navbar";

const sawarabi = Sawarabi_Mincho({
  subsets: ["latin"],
  weight: ["400", "400"],
});

export const metadata: Metadata = {
  title: "これ何のWiki?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={sawarabi.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
